
server:
  port: 8863
spring:
  application:
    name: service-consumer         #应用名称(集群下相同)
eureka:
  instance:
    hostname: serviceConsumer             #主机名， 不配置的时候按照系统主机名
    prefer-ip-address: true        #是否使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    #ip:port
  client:
    register-with-eureka: false     #是否将自己注册到注册中心 默认 true    //服务消费者本次只调用服务 不提供服务
    registry-fetch-interval-seconds: 10  #表示 Eureka Client 间隔多久去服务器拉取注册信息 默认 30 秒
    service-url:                   #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@127.0.0.1:8761/eureka/,http://root:123456@127.0.0.1:8762/eureka/    #集群 下项目注册

#基于配置的随机策略（局部）
service-provider:            #调用的服务的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


