server:
  port: 7070
spring:
  application:
    name: consul-service-provide
  cloud:
    consul:
      #注册中心的访问地址
      host: 10.10.10.1
#      host: localhost
      port: 8500
      #服务提供者信息
      discovery:
        register: true                                 #是否需要注册
        instance-id: ${spring.application.name}-01     #注册实例 id（必须唯一）
        service-name: ${spring.application.name}       #服务名称
        port: ${server.port}                           #服务端口
        prefer-agent-address: true                     #是否使用IP地址注册
        ip-address: ${spring.cloud.client.ip-address}  #服务请求地址
        health-check-interval: 15s
        health-check-path: /actuator/health
