
server:
  port: 8862
spring:
  application:
    name: service-provider         #应用名称(集群下相同)
#  security:
#    user:
#      name: root
#      password: 123456
eureka:
  instance:
    hostname: serviceProvider02              #主机名， 不配置的时候按照系统主机名
    prefer-ip-address: true        #是否使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    #ip:port
  client:
    service-url:                   #注册中心对外暴露的注册地址
      defaultZone: http://root:123456@127.0.0.1:8761/eureka/,http://root:123456@127.0.0.1:8762/eureka/    #集群 下项目注册
#度量指标健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown #开启 shutdown 端点访问
  endpoint:
    shutdown:
      enabled: true # 开启 shutdown 实现优雅停服

