
server:
  port: 8762
spring:
  application:
    name: eureka-server             #应用名称(集群下相同)
  #安全认证
  security:
    user:
      name: root
      password: 123456
eureka:
  instance:
    hostname: eureka02             #主机名， 不配置的时候按照系统主机名
    prefer-ip-address: true        #是否使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    #ip:port
  client:
#    register-with-eureka: false     #是否将自己注册到注册中心 默认 true                #单节点
#    fetch-registry: false           #是否从注册中心获取服务注册信息  默认 true          #单节点
    register-with-eureka: true     #是否将自己注册到注册中心 默认 true
    fetch-registry: true           #是否从注册中心获取服务注册信息  默认 true
    service-url:                    #注册中心对外暴露的注册地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #单节点
      defaultZone: http://root:123456@127.0.0.1:8761/eureka/    #集群 下项目注册
  server:
    enable-self-preservation: true #自我保护模式
    eviction-interval-timer-in-ms: 60000 #清理间隔 （毫秒 默认 60*1000）
